apiVersion: v1
kind: Pod
metadata:
  name: dump-process-memory
  labels:
    app: ubuntu
spec:
  containers:
  - image: ghcr.io/lightspin-tech/light-k8s-attack-simulations/k8s-attack-simulation:latest
    command: ["src/shell-dump-process-memory.sh"]
    imagePullPolicy: Always
    name: simulation
    securityContext:
        capabilities:
          add: ["SYS_PTRACE"]
