apiVersion: v1
kind: Pod
metadata:
  name: logs-removal
  labels:
    app: ubuntu
spec:
  containers:
  - image: ghcr.io/lightspin-tech/light-k8s-attack-simulations/k8s-attack-simulation:latest
    command: ["src/shell-logs-removal.sh"]
    imagePullPolicy: Always
    name: simulation
