apiVersion: v1
kind: Pod
metadata:
  name: modify-ssh-authorized-keys
  labels:
    app: ubuntu
spec:
  containers:
  - image: ghcr.io/lightspin-tech/light-k8s-attack-simulations/k8s-attack-simulation:latest
    command: ["src/shell-modify-ssh-authorized-keys.sh"]
    imagePullPolicy: Always
    name: simulation
