apiVersion: v1
kind: Pod
metadata:
  name: outbound-connection-to-miner
  labels:
    app: ubuntu
spec:
  containers:
  - image: ghcr.io/lightspin-tech/light-k8s-attack-simulations/k8s-attack-simulation:latest
    command: ["src/shell-outbound-connection-to-miner.sh"]
    imagePullPolicy: Always
    name: simulation
